//In the console, define a variable and set it equal to an integer value. Then write code that will console.log “TRUE” if the integer stored in your variable is divisible by 5, and “FALSE” otherwise. Try your code with the following values: 5, 55, 37


const number = 11;
  if (number % 5==0) {
console.log(true);
  }
else{
  console.log(false);
}



//In the console, define two variables and set them each equal to an integer value. Then write code that will console.log “TRUE” if the sum of the numbers is less than 100, and “FALSE” otherwise.Try your code with the following pairs of values: (22,15), (83,34)


/*const firstNumb=15;
const secondNumb=22;
const sumNumb =(firstNumb + secondNumb);
  if (sumNumb < 100) {
console.log("True");
  }
else{
  console.log("false");
}
*/


//Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

let sum = 0;
let numb1 = 1;
let numb2 = 2;

while (numb2 < 4000000) {
 sum += numb2 % 2 === 0 ? numb2 : 0;
    numb2 = numb1 + numb2;
    numb1 = numb2 - numb1;
}
console.log(sum);